import type { StoryObj } from '@storybook/nextjs';
declare const meta: Meta<FC<import(".").ISelectProps>>;
export default meta;
type Story = StoryObj<typeof meta>;
export declare const Default: Story;
export declare const WithPlaceholder: Story;
export declare const Disabled: Story;
export declare const NotClearable: Story;
export declare const HideChecked: Story;
export declare const WithSearch: Story;
export declare const PortalSelectVariant: Story;
export declare const CustomRenderOption: Story;
export declare const LoadingState: Story;
export declare const FormField: Story;
export declare const FilterSelector: Story;
export declare const VersionSelector: Story;
export declare const SettingsDropdown: Story;
export declare const VariantComparison: Story;
export declare const Playground: Story;
