import type { ConversationVariable, EnvironmentVariable, Node, NodeOutPutVar, ToolWithProvider, ValueSelector, Var } from '@/app/components/workflow/types';
import type { RAGPipelineVariable } from '@/models/pipeline';
import type { SchemaTypeDefinition } from '@/service/use-common';
import { InputVarType, VarType } from '@/app/components/workflow/types';
import { Type } from '../../../llm/types';
export declare const isSystemVar: (valueSelector: ValueSelector) => boolean;
export declare const isGlobalVar: (valueSelector: ValueSelector) => boolean;
export declare const isENV: (valueSelector: ValueSelector) => boolean;
export declare const isConversationVar: (valueSelector: ValueSelector) => boolean;
export declare const isRagVariableVar: (valueSelector: ValueSelector) => boolean;
export declare const isSpecialVar: (prefix: string) => boolean;
export declare const hasValidChildren: (children: any) => boolean;
export declare const inputVarTypeToVarType: (type: InputVarType) => VarType;
export declare const varTypeToStructType: (type: VarType) => Type;
export declare const removeFileVars: (nodeWithVars: NodeOutPutVar[]) => any[];
export declare const toNodeOutputVars: (nodes: any[], isChatMode: boolean, filterVar: (_payload: Var, _selector: ValueSelector) => boolean, environmentVariables: EnvironmentVariable[] | undefined, conversationVariables: ConversationVariable[] | undefined, ragVariables: RAGPipelineVariable[] | undefined, allPluginInfoList: Record<string, ToolWithProvider[]>, schemaTypeDefinitions?: SchemaTypeDefinition[]) => NodeOutPutVar[];
export declare const getVarType: ({ parentNode, valueSelector, isIterationItem, isLoopItem, availableNodes, isChatMode, isConstant, environmentVariables, conversationVariables, ragVariables, allPluginInfoList, schemaTypeDefinitions, preferSchemaType, }: {
    valueSelector: ValueSelector;
    parentNode?: Node | null;
    isIterationItem?: boolean;
    isLoopItem?: boolean;
    availableNodes: any[];
    isChatMode: boolean;
    isConstant?: boolean;
    environmentVariables?: EnvironmentVariable[];
    conversationVariables?: ConversationVariable[];
    ragVariables?: RAGPipelineVariable[];
    allPluginInfoList: Record<string, ToolWithProvider[]>;
    schemaTypeDefinitions?: SchemaTypeDefinition[];
    preferSchemaType?: boolean;
}) => VarType;
export declare const toNodeAvailableVars: ({ parentNode, t, beforeNodes, isChatMode, environmentVariables, conversationVariables, ragVariables, filterVar, allPluginInfoList, schemaTypeDefinitions, }: {
    parentNode?: Node | null;
    t?: any;
    beforeNodes: Node[];
    isChatMode: boolean;
    environmentVariables?: EnvironmentVariable[];
    conversationVariables?: ConversationVariable[];
    ragVariables?: RAGPipelineVariable[];
    filterVar: (payload: Var, selector: ValueSelector) => boolean;
    allPluginInfoList: Record<string, ToolWithProvider[]>;
    schemaTypeDefinitions?: SchemaTypeDefinition[];
}) => NodeOutPutVar[];
export declare const getNodeInfoById: (nodes: any, id: string) => any;
export declare const getNodeUsedVars: (node: Node) => ValueSelector[];
export declare const getNodeUsedVarPassToServerKey: (node: Node, valueSelector: ValueSelector) => string | string[];
export declare const findUsedVarNodes: (varSelector: ValueSelector, availableNodes: Node[]) => Node[];
export declare const updateNodeVars: (oldNode: Node, oldVarSelector: ValueSelector, newVarSelector: ValueSelector) => Node;
export declare const getNodeOutputVars: (node: Node, isChatMode: boolean) => ValueSelector[];
