import type { LLMNodeType } from './types';
declare const useConfig: (id: string, payload: LLMNodeType) => {
    readOnly: boolean;
    isChatMode: boolean;
    inputs: any;
    isChatModel: boolean;
    isCompletionModel: boolean;
    hasSetBlockStatus: {
        history: any;
        query: any;
        context: any;
    };
    shouldShowContextTip: any;
    isVisionModel: any;
    handleModelChanged: any;
    handleCompletionParamsChange: any;
    isShowVars: boolean;
    handleVarListChange: any;
    handleVarNameChange: any;
    handleAddVariable: any;
    handleAddEmptyVariable: any;
    handleContextVarChange: any;
    filterInputVar: any;
    filterVar: any;
    availableVars: any[];
    availableNodesWithParent: any[];
    handlePromptChange: any;
    handleMemoryChange: any;
    handleSyeQueryChange: any;
    handleVisionResolutionEnabledChange: any;
    handleVisionResolutionChange: any;
    isModelSupportStructuredOutput: any;
    handleStructureOutputChange: any;
    structuredOutputCollapsed: any;
    setStructuredOutputCollapsed: any;
    handleStructureOutputEnableChange: any;
    filterJinja2InputVar: any;
    handleReasoningFormatChange: any;
};
export default useConfig;
